name: Docker Publish

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push CarService
        uses: docker/build-push-action@v5
        with:
          context: microservices/CarService
          file: microservices/CarService/CarService.WebApi/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/carservice:latest

      - name: Build and push EmployeeService
        uses: docker/build-push-action@v5
        with:
          context: microservices/EmployeeService
          file: microservices/EmployeeService/EmployeeService.WebApi/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/employeeservice:latest

      - name: Build and push BookingService
        uses: docker/build-push-action@v5
        with:
          context: microservices/BookingService
          file: microservices/BookingService/BookingService.WebApi/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/bookingservice:latest