name: Docker Publish Multi-Service (No Matrix)

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Questo step trasforma il nome del repo in minuscolo
      - name: Lowercase Repo Name
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- CAR SERVICE ---
      - name: Build and push Car Service
        uses: docker/build-push-action@v5
        with:
          context: ./microservices
          file: ./microservices/CarService/CarService.WebApi/Dockerfile 
          push: true
          # Usiamo ${{ env.REPO_LOWER }} invece di github.repository
          tags: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/car-service:latest

      # --- EMPLOYEE SERVICE ---
      - name: Build and push Employee Service
        uses: docker/build-push-action@v5
        with:
          context: ./microservices
          file: ./microservices/EmployeeService/EmployeeService.WebApi/Dockerfile 
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/employee-service:latest

      # --- BOOKING SERVICE ---
      # - name: Build and push Booking Service
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./microservices/BookingService/BookingService.WebApi/Dockerfile 
      #     push: true
      #     tags: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/booking-service:latest