name: Publish Shared Libraries

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
        run: |
          dotnet restore microservices/CarService/CarService.slnx
          dotnet restore microservices/EmployeeService/EmployeeService.slnx

      - name: Pack Projects
        run: |
          dotnet pack microservices/CarService/CarService.Shared/CarService.Shared.csproj -c Release -o ./nuget-packages --no-restore
          dotnet pack microservices/CarService/CarService.ClientHttp/CarService.ClientHttp.csproj -c Release -o ./nuget-packages --no-restore
          dotnet pack microservices/EmployeeService/EmployeeService.Shared/EmployeeService.Shared.csproj -c Release -o ./nuget-packages --no-restore
          dotnet pack microservices/EmployeeService/EmployeeService.ClientHttp/EmployeeService.ClientHttp.csproj -c Release -o ./nuget-packages --no-restore

      - name: Push to GitHub Packages
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
        run: |
          dotnet nuget push "./nuget-packages/*.nupkg" \
            --api-key ${{ secrets.NUGET_TOKEN }} \
            --source "github" \
            --configfile "${{ github.workspace }}/nuget.config" \
            --skip-duplicate